config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'configurations#edit'
  post '/' => 'configurations#update'
  get 'data' => 'configurations#data'
  get 'crossdomain.xml' => 'configurations#crossdomain'
  get 'spritesheet' => 'configurations#spritesheet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
	def edit
		@data = JSON.parse(File.read('app/assets/javascripts/config.json'))
	end

	def update
		payline_rows = params[:payline_rows] ? params[:payline_rows].map { |n| n.to_i } : []

		puts(params)

		data = {
			"game":{
				"playfield":{"columns": params[:cols], "rows": params[:rows]},
				"payline": {"type": params[:payline_type], "rows": payline_rows},
				"player":{"startBalance": params[:start_balance], "wager": params[:wager]},
				"symbols": {"spritesheet_url": "assets/spritesheet.png", "count": params[:symbol_count], "info":[{"x":0, "y":0, "width":256, "height":256, "multiplier": params["multiplier"][0]}, {"x":256, "y":0, "width":256, "height":256, "multiplier": params["multiplier"][1]}, {"x":512, "y":0, "width":256, "height":256, "multiplier": params["multiplier"][2]}, {"x":768, "y":0, "width":256, "height":256, "multiplier": params["multiplier"][3]}, {"x":0, "y":256, "width":256, "height":256, "multiplier": params["multiplier"][4]}, {"x":256, "y":256, "width":256, "height":256, "multiplier": params["multiplier"][5]}, {"x":512, "y":256, "width":256, "height":256, "multiplier": params["multiplier"][6]}, {"x":768, "y":256, "width":256, "height":256, "multiplier": params["multiplier"][7]}, {"x":0, "y":512, "width":256, "height":256, "multiplier": params["multiplier"][8]},{"x":256, "y":512, "width":256, "height":256, "multiplier": params["multiplier"][9]}]}
			}
		}

		File.open('app/assets/javascripts/config.json', 'w') do |f|
			f.write(JSON.pretty_generate(data))
		end

		flash[:success] = %Q[Success! <a href="https://zpantoine.bitbucket.io">You can see the app here.</a>]
		redirect_to root_path
	end

	def data
		send_file 'app/assets/javascripts/config.json', :disposition => 'inline'
	end

	def crossdomain
		send_file 'app/assets/xml/crossdomain.xml', :disposition => 'inline'
	end

	def spritesheet
		send_file 'app/assets/images/spritesheet.png', :disposition => 'inline'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/edit.html.erb
<h2>Edit the configuration file</h2>
<%= render 'layouts/form' %>

app/views/layouts/_form.html.erb
<% content_for :js do %>
	<script>

		var numRows;
		var rowSelector;
		var singleRowSelector;
		var anyRowSelector;
		var activeRows;
		var numRows;

		$(document).ready(onLoad);

		function onLoad() {

			rowSelector = document.getElementById("rows");
			anyRowSelector = document.getElementById("payline_type_any");
			singleRowSelector = document.getElementById("payline_type_single");
			activeRows = document.getElementById("active-row-selectors");

			anyRowSelector.onclick = updateActiveRows;
			singleRowSelector.onclick = updateActiveRows;
			rowSelector.onchange = updateCheckboxes;

			updateActiveRows();
		}

		function updateActiveRows() {
			if(singleRowSelector.checked) {
				activeRows.style.display = "inline";

				if(numRows != document.getElementById("rows").value) {
					updateCheckboxes();
				}
			}
			else {
				activeRows.style.display = "none";
			}
		}

		function updateCheckboxes() {
			numRows = rowSelector.value;
			$('#active-row-selectors').empty();
			$('#active-row-selectors').append("<span><label for='active_rows:'>Active rows:</label></span>");

			var array = <%= @data["game"]["payline"]["rows"] %>
			console.log(array)
			for(var i=0;i < numRows;++i) {

				var checked = array.indexOf(i) > -1 ? 'checked' : '';
				var htmlString = '<span><input type="checkbox" name="payline_rows[]" id="payline_rows_' + i + '" value='+i+' ' + checked + '/><label for="payline_rows_">' + (i + 1) + '</label></span>';
				console.log(htmlString);
				$('#active-row-selectors').append(htmlString);
			}
		}

	</script>
<% end %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_tag do %>
			<h3>Playfield</h3>
			<hr/>
			<%= label_tag(:cols, "Columns:") %>
			<%= select_tag(:cols, options_for_select([['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8]], @data["game"]["playfield"]["columns"])) %>

			<span class="separator-x">x</span>

			<%= label_tag(:rows, "Rows:") %>
			<%= select_tag(:rows, options_for_select([['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8]], @data["game"]["playfield"]["rows"])) %>

			<h3>Paylines</h3>
			<hr/>

			<div id="payline-selectors">
				<span>
					<%= label_tag(:payline_type, "Any row:") %>
					<%= radio_button_tag(:payline_type, "any", @data["game"]["payline"]["type"] == "any") %>
				</span>
				<span>
					<%= label_tag(:payline_type, "Single row:") %>
					<%= radio_button_tag(:payline_type, "single", @data["game"]["payline"]["type"] == "single") %>
				</span>
			</div>

			<div id="active-row-selectors">
			</div>
			
			<h3>Player</h3>
			<hr/>

			<div id="player-options">
				<%= label_tag(:start_balance,  "Starting balance:") %>
				<%= number_field_tag(:start_balance, @data["game"]["player"]["startBalance"], min: 0, step: 100) %><br/>

				<%= label_tag(:wager,  "Wager:") %>
				<%= number_field_tag(:wager, @data["game"]["player"]["wager"], min: 0, step: 5) %>
			</div>

			<h3>Symbols</h3>
			<hr/>

			<%= label_tag(:symbol_count, "Number of symbols:") %>
			<%= select_tag(:symbol_count, options_for_select([['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]], @data["game"]["symbols"]["count"])) %><br/>


			<%= label_tag(:symbol_count, "Multiplier Percent:") %><br/>

			<% image = MiniMagick::Image.open(spritesheet_url) %>
			<% images = @data["game"]["symbols"]["info"] %>
			
			<%  images.each_with_index do |info, i| %>
				<% scale = 100.0 / info["width"] %>
				<div class="symbolContainer">
					<div class="symbol" style = "background-image: url(<%= spritesheet_path %>);background-size: <%= image.width * scale %>%; <%= image.height * scale %>%;background-position: -<%= info['x'] * scale %>px -<%= info['y'] * scale %>px;"></div>
					<%= number_field_tag("multiplier[]", info["multiplier"], min: 10, class: "multiplierField center") %>
				</div>

			<% end %>

			<div class="center clear">
				<%= submit_tag("Save changes", class: 'btn btn-primary') %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Configurator", root_path, id: "logo" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Configurator</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :js %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, sanitize(msg), {class: "alert alert-#{msg_type} center"}) %>
    <% end %>
    <%= yield %>
  </body>
</html>